# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff648a7d783079cb96fb9ee0efade9f07be36bc2ab528c0460711cd817b4c7626361cadcd0d008951b15a977728f8d14bb7169e53921e7be3294b960b082b21a

test:
  secret_key_base: db4fdd47d204146d72f8f8f944a3ee8ea1cd7845a3531422e09fdf6cb8c738e4ac370746f8bfed1b9ac4cf709c1aa7139279415383d2d347722279e112bbe5dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
